version: '3.8'
services:
  web:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
    command: npm start
    ports:
      - "3001:3000"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cvfuser
      POSTGRES_PASSWORD: k1m2ll345
      POSTGRES_DB: cvfreelancer
    ports:
      - "5432:5432"
